pin-edu-sns/config/routes.rb
# -*- coding: utf-8 -*-
# -- 用户认证相关 --
def match_auth_routes
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

# -- 设置 --
def match_account_routes
  # 基本信息
  get  "/setting"                     => "setting#base"
  put  "/setting"                     => "setting#base_submit"

  # 设置密码
  get '/setting/password'             => "setting#password"
  put '/setting/password'             => "setting#password_submit"

  # 头像设置
  get  "/setting/avatar"              => 'setting#avatar'
  get  '/setting/temp_avatar'         => 'setting#temp_avatar'
  post "/setting/avatar_submit_raw"   => 'setting#avatar_submit_raw'
  post "/setting/avatar_submit_crop"  => 'setting#avatar_submit_crop'
end

MindpinEduSns::Application.routes.draw do
  namespace :auth do
    # ---------------- 首页和欢迎页面 ---------
    root :to => 'sessions#new'
    match_auth_routes
    match_account_routes
  end

  ###
  namespace :admin do
    get '/search' => 'search#index'
    get '/search/:kind' => 'search#show'

    get '/setting/password'             => "setting#password"
    put '/setting/password'             => "setting#password_submit"


    # 管理员多级目录
    resources :upload_document_dirs do
      collection do
        post :create_folder
      end
    end

    resources :upload_documents do
      collection do
        post :file_put
      end
    end


    resources :teachers do
      collection do
        get :import_from_csv_page
        post :import_from_csv
      end
      member do
        get :password
        put :password_submit
        get 'course/:course_id', :action => 'course_students'
      end
    end

    resources :students do
      collection do
        get :import_from_csv_page
        post :import_from_csv
      end
      member do
        get :password
        put :password_submit
        put :upload_attachment
      end
    end

    resources :courses do
      member do
        get  :add_teacher_page
        put  :add_teacher
        get  :select_students
        put  :set_students
        get  :select_cover_page
        post :select_cover
      end
      collection do
        get  :import_from_csv_page
        post :import_from_csv
      end
      resources :course_resources, :shallow => true
    end
    resources :teams do
      member do
        get  :select_students
        put  :set_students
      end
      collection do
        get  :import_from_csv_page
        post :import_from_csv
      end
    end
    
    resources :categories do
      collection do
        get :import_from_yaml_page
        post :import_from_yaml
      end
    end

    resources :course_teachers do
      member do
        get :select_students_page
        put :select_students
        put :update_location
        get :edit_time_expression
        put :update_time_expression
        get :show_time_expression
      end

      resources :course_change_records, :shallow => true
    end

    resources :teaching_plans do
      collection do
        get :import_from_csv_page
      end
    end

    resources :course_surveys do
      collection do
        get :show_courses_by_semester
        get :show_teachers_by_course
      end
    end

    resources :mentor_notes

    resources :mentor_courses

    resources :course_score_records do
      collection do
        get :get_students_by_course
      end
    end
    
    resources :announcements

    resources :test_questions
    
    root :to=>"index#index"
  end
  ###
  # ----------------------------------------------------------------





  root :to => 'index#index'
  # 工作台
  get '/dashboard' => 'index#dashboard'
  # 搜索
  get '/search' => 'search#index'
  get '/search/:kind' => 'search#show'
  post '/batch_destroy' => 'index#batch_destroy'

  # --- 用户
  resources :users

  resources :teachers

  resources :students

  # --- 老师问答
  resources :questions, :shallow => true do
    resources :answers do
      collection do
        get :received
      end
    end
  end

  # ----------------------

  # 所有类型的评论都在这里，不单独定义
  resources :comments do
    collection do
      get 'show_model_comments'
      get 'received' # 我收到的评论
    end
  end
  
  resources :short_messages do
    member do
      put :read
    end

    collection do
      get :inbox
      get :outbox
    end
  end

  # --- 作业
  resources :homeworks do
    collection do
      post :create_teacher_attachment
      post :create_student_upload
    end
    
    member do
      get :download_teacher_zip
    end
  end

  resources :homework_assigns, :only => [:show] do
    member do
      get :download_student_zip
      put :set_finished
      put :set_submitted
    end
  end

  delete 'homeworks/teacher_attachment/:id/destroy' => 'homeworks#destroy_teacher_attachment'
  delete 'homeworks/requirement/:id/destroy' => 'homeworks#destroy_requirement'

  resources :homeworks, :student

  resources :teachers

  # 查看当前用户参与或负责的课程
  resources :course_surveys, :shallow => true do
    resources :course_survey_records
  end

  resources :mentor_students


  resources :courses do
    collection do
      get :curriculum
      get :next_for_student
      get :next_for_teacher
      get :subscriptions
    end

    member do
      put :subscribe
      get :edit_chapters

      get :nav_teachers
      get :nav_chapters
      get :nav_homeworks
      get :nav_ctest
      get :browse_chapters
    end

    resources :course_resources, :shallow => true
  end

  # --------------------

  # web
  get    '/file' => 'media_resources#index'
  get    '/file/*path' => 'media_resources#file', :format => false

  put    '/file_put' => 'media_resources#upload_file'
  post   '/file/create_folder' => 'media_resources#create_folder'
  delete '/file/*path' => 'media_resources#destroy'

  get    '/file_attr/*path/edit_tag' => 'media_resources#edit_tag'
  put    '/file_attr/*path/update_tag' => 'media_resources#update_tag'

  get  'file_show/*path' => 'media_resources#file_show', :format => false

  post '/upload' => 'file_entities#upload'
  post '/kindeditor_upload' => 'file_entities#kindeditor_upload'
  get  '/download/:download_id' => 'file_entities#download'
  post   '/file_entities/:id/re_encode'  => 'file_entities#re_encode'

  get '/media_resources/lazyload_sub_dynatree' => 'media_resources#lazyload_sub_dynatree'
  get '/media_resources/reload_dynatree'       => 'media_resources#reload_dynatree'
  put '/media_resources/move' => 'media_resources#move'

  resources :media_shares

  get '/media_shares/users/:user_id'       => 'media_shares#share'
  get '/media_shares/users/:user_id/*path' => 'media_shares#share'



  # api
  get    '/api/file/*path'            => 'media_resources_api#get_file'
  put    '/api/file_put/*path'        => 'media_resources_api#put_file'
  get    '/api/metadata/*path'        => 'media_resources_api#get_metadata'
  get    '/api/delta'                 => 'media_resources_api#get_delta'
  post   '/api/fileops/create_folder' => 'media_resources_api#create_folder'
  delete '/api/fileops/delete'        => 'media_resources_api#delete'





  # 公共资源
  resources :public_resources do
    collection do
      post :share
      put :upload
    end

    member do
      put :update_tag
    end
  end

  get '/public_resources/user/:id/file/*path' => 'public_resources#dir'
  get '/public_resources/user/:id/index_file/:file_entity_id' => 'public_resources#index_file'
  put '/public_resources/upload/*path' => 'public_resources#upload'
  get '/user_complete_search' => 'index#user_complete_search'
  get '/check_tip_messages' => 'index#check_tip_messages'

  get    '/tags/:tag_name'             => 'tags#show'
  get    '/tags/:tag_name/mine'        => 'tags#show_mine'
  get    '/tags/:tag_name/public'      => 'tags#show_public'
  get    '/tags/:tag_name/shared'      => 'tags#show_shared'

  resources :categories do
    member do
      get :lazyload_sub_dynatree
    end
  end

  resources :announcements do

    member do
      put :announce
    end
  end

  get '/c1/show' => 'c1#show'
  resources :e1
  resources :e2
  get '/f1/show' => 'f1#show'
  get '/d1/show' => 'd1#show'
  get 'g2/show'  => 'g2#show'
  get 'g3/show'  => 'g3#show'
  get 'g4/show'  => 'g4#show'

  get 'g1/show'  => 'g1#show'

  resources :i1
  resources :j1
  resources :k1
  resources :j2
  resources :j3

  resources :o1 do
    collection do
      get :zhaoyun
      get :zhugeliang
      get :faq_form
      get :question
    end
  end

  resources :test_papers

  resources :teaching_plans do
    member do
      get :preview
    end

    resources :chapters, :shallow => true do
      member do
        post :update_title
        post :update_desc
      end
      resources :course_wares, :shallow => true do
        member do
          post :update_title
          post :update_desc
          put :upload_file
          put :link_file
        end
      end
    end

    resources :test_questions, :shallow => true do
    end
  end


  

end

pin-edu-sns/app/controllers/public_resources_controller.rb
# -*- coding: utf-8 -*-
class PublicResourcesController < ApplicationController
  # 公共资源列表
  def index
    if params[:category_id].blank?
      @sub_categories = Category.roots
      @public_resources = PublicResource.no_category
      @navigation_categories = []
    else
      @category = Category.find(params[:category_id])
      @sub_categories = @category.children
      @public_resources = PublicResource.of_category(@category)
      @navigation_categories = @category.self_and_ancestors
      @parent_category = @category.parent
    end
    @items = @sub_categories + @public_resources
  end

  # 分享到公共资源
  # for ajax
  def share
    current_resource = MediaResource.find(params[:resource_id])
    category = Category.find_by_id(params[:category_id])
    public_resource_id = current_resource.share_public(category)
    render :text => 'ok'
  end

  def update_tag
    resource = PublicResource.find(params[:id])
    resource.set_tags_by!(current_user, params[:tag_names])
    render :json => resource.tag_list
  end

  # 上传到公共资源 
  def upload
    if params[:file].blank?
      flash_error "先选择一个文件上传"
    else
      PublicResource.upload_by_user(current_user, params[:file])
    end

    redirect_to :back
  end


  
  def index_file
    id = params[:file_entity_id]

    file_entity = FileEntity.find(id)
    return send_file file_entity.attach.path
  end

end

pin-edu-sns/app/views/public_resources/parts/_forms.html.haml
.page-media-resources-forms
  = flash[:error]

  = form_tag '/public_resources/upload', :method=>'put', :multipart=>true, :class=>'upload-public-file' do
    = hidden_field_tag :current_path, @current_dir.blank? ? '/' : @current_dir.path
    = file_field_tag :file
    %a.form-submit-button 上传文件

pin-edu-sns/app/views/public_resources/parts/_resource_tag.html.haml
%span 标签:

.resource-tag-list
  .values{:style=>"float:left;",:"data-value"=>resource.tag_list.join(",")}
    - resource.tag_list.each do |tag_name|
      = link_to tag_name, "/tags/#{tag_name}", :style => 'padding:4px;'
  - if resource.creator == current_user
    = link_to "修改", 'javascript:;',:style=>"font-size:12px;",:class=>"edit-tag-form-button"

.resource-edit-tags-form{:style=>"display:none;"}
  = text_field_tag :tag, resource.tag_list * ",",:class=>"tag_names",:'data-url'=> update_tag_public_resource_path(resource)
  = link_to '确定', 'javascript:;', :class => 'submit'
  = link_to '取消', 'javascript:;', :class => 'cancel'

pin-edu-sns/app/views/public_resources/parts/_resources.html.haml
.page-media-resources.public
  - items.each do |item|
    - if item.is_a?(Category)
      :ruby
        category = item
        cover_src = '/assets/covers/category.small.png'
        title = category.name
        resource_url = "/public_resources?category_id=#{category.id}"
      .media-resource
        .meta-box
          .cover{:'data-src'=>cover_src}
          .detail
            .link.open= link_to '打开分类', resource_url
          .title= title

    - else
      :ruby
        public_resource = item
        cover_src = file_entity_cover_src public_resource.real_file_entity
        title = truncate_u(public_resource.name, 10)
        resource_url = download_link(public_resource.real_file_entity, public_resource.name)

      .media-resource
        .meta-box
          .cover{:'data-src'=>cover_src}
          .detail
            .link.open= link_to '下载资源', resource_url
          .title= title
          .tags= render 'public_resources/parts/resource_tag', :resource=> public_resource

pin-edu-sns/app/views/public_resources/parts/_resources_tag.html.haml
%span 标签:

.resource-tag-list
  .values{:style=>"float:left;",:"data-value"=>resource.tag_list.join(",")}
    - resource.tag_list.each do |tag_name|
      = link_to tag_name, "/tags/#{tag_name}", :style => 'padding:4px;'
  - if resource.creator == current_user
    = link_to "修改", 'javascript:;',:style=>"font-size:12px;",:class=>"edit-tag-form-button"

.resource-edit-tags-form{:style=>"display:none;"}
  = text_field_tag :tag, resource.tag_list * ",",:class=>"tag_names",:'data-url'=> File.join('/file_attr', resource.path,'update_tag')
  = link_to '确定', 'javascript:;', :class => 'submit'
  = link_to '取消', 'javascript:;', :class => 'cancel'