pin-edu-sns/config/routes.rb
# -*- coding: utf-8 -*-
# -- 用户认证相关 --
def match_auth_routes
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

# -- 设置 --
def match_account_routes
  # 基本信息
  get  "/setting"                     => "setting#base"
  put  "/setting"                     => "setting#base_submit"

  # 设置密码
  get '/setting/password'             => "setting#password"
  put '/setting/password'             => "setting#password_submit"

  # 头像设置
  get  "/setting/avatar"              => 'setting#avatar'
  get  '/setting/temp_avatar'         => 'setting#temp_avatar'
  post "/setting/avatar_submit_raw"   => 'setting#avatar_submit_raw'
  post "/setting/avatar_submit_crop"  => 'setting#avatar_submit_crop'
end

MindpinEduSns::Application.routes.draw do
  namespace :auth do
    # ---------------- 首页和欢迎页面 ---------
    root :to => 'sessions#new'
    match_auth_routes
    match_account_routes
  end

  ###
  namespace :admin do
    get '/search' => 'search#index'
    get '/search/:kind' => 'search#show'

    get '/setting/password'             => "setting#password"
    put '/setting/password'             => "setting#password_submit"


    # 管理员多级目录
    resources :upload_document_dirs do
      collection do
        post :create_folder
      end
    end

    resources :upload_documents do
      collection do
        post :file_put
      end
    end


    resources :teachers do
      collection do
        get :import_from_csv_page
        post :import_from_csv
      end
      member do
        get :password
        put :password_submit
        get 'course/:course_id', :action => 'course_students'
      end
    end

    resources :students do
      collection do
        get :import_from_csv_page
        post :import_from_csv
      end
      member do
        get :password
        put :password_submit
        put :upload_attachment
      end
    end

    resources :courses do
      member do
        get  :add_teacher_page
        put  :add_teacher
        get  :select_students
        put  :set_students
        get  :select_cover_page
        post :select_cover
      end
      collection do
        get  :import_from_csv_page
        post :import_from_csv
      end
      resources :course_resources, :shallow => true
    end
    resources :teams do
      member do
        get  :select_students
        put  :set_students
      end
      collection do
        get  :import_from_csv_page
        post :import_from_csv
      end
    end
    
    resources :categories do
      collection do
        get :import_from_yaml_page
        post :import_from_yaml
      end
    end

    resources :course_teachers do
      member do
        get :select_students_page
        put :select_students
        put :update_location
        get :edit_time_expression
        put :update_time_expression
        get :show_time_expression
      end

      resources :course_change_records, :shallow => true
    end

    resources :teaching_plans do
      collection do
        get :import_from_csv_page
      end
    end

    resources :course_surveys do
      collection do
        get :show_courses_by_semester
        get :show_teachers_by_course
      end
    end

    resources :mentor_notes

    resources :mentor_courses

    resources :course_score_records do
      collection do
        get :get_students_by_course
      end
    end
    
    resources :announcements

    resources :test_questions
    
    root :to=>"index#index"
  end
  ###
  # ----------------------------------------------------------------





  root :to => 'index#index'
  # 工作台
  get '/dashboard' => 'index#dashboard'
  # 搜索
  get '/search' => 'search#index'
  get '/search/:kind' => 'search#show'
  post '/batch_destroy' => 'index#batch_destroy'

  # --- 用户
  resources :users

  resources :teachers

  resources :students

  # --- 老师问答
  resources :questions, :shallow => true do
    resources :answers do
      collection do
        get :received
      end
    end
  end

  # ----------------------

  # 所有类型的评论都在这里，不单独定义
  resources :comments do
    collection do
      get 'show_model_comments'
      get 'received' # 我收到的评论
    end
  end
  
  resources :short_messages do
    member do
      put :read
    end

    collection do
      get :inbox
      get :outbox
    end
  end

  # --- 作业
  resources :homeworks do
    collection do
      post :create_teacher_attachment
      post :create_student_upload
    end
    
    member do
      get :download_teacher_zip
    end
  end

  resources :homework_assigns, :only => [:show] do
    member do
      get :download_student_zip
      put :set_finished
      put :set_submitted
    end
  end

  delete 'homeworks/teacher_attachment/:id/destroy' => 'homeworks#destroy_teacher_attachment'
  delete 'homeworks/requirement/:id/destroy' => 'homeworks#destroy_requirement'

  resources :homeworks, :student

  resources :teachers

  # 查看当前用户参与或负责的课程
  resources :course_surveys, :shallow => true do
    resources :course_survey_records
  end

  resources :mentor_students


  resources :courses do
    collection do
      get :curriculum
      get :next_for_student
      get :next_for_teacher
      get :subscriptions
    end

    member do
      put :subscribe
      get :edit_chapters

      get :nav_teachers
      get :nav_chapters
      get :nav_homeworks
      get :nav_ctest
      get :browse_chapters
    end

    resources :course_resources, :shallow => true
  end

  # --------------------

  # web
  get    '/file' => 'media_resources#index'
  get    '/file/*path' => 'media_resources#file', :format => false

  put    '/file_put' => 'media_resources#upload_file'
  post   '/file/create_folder' => 'media_resources#create_folder'
  delete '/file/*path' => 'media_resources#destroy'

  get    '/file_attr/*path/edit_tag' => 'media_resources#edit_tag'
  put    '/file_attr/*path/update_tag' => 'media_resources#update_tag'

  get  'file_show/*path' => 'media_resources#file_show', :format => false

  post '/upload' => 'file_entities#upload'
  post '/kindeditor_upload' => 'file_entities#kindeditor_upload'
  get  '/download/:download_id' => 'file_entities#download'
  post   '/file_entities/:id/re_encode'  => 'file_entities#re_encode'

  get '/media_resources/lazyload_sub_dynatree' => 'media_resources#lazyload_sub_dynatree'
  get '/media_resources/reload_dynatree'       => 'media_resources#reload_dynatree'
  put '/media_resources/move' => 'media_resources#move'

  resources :media_shares

  get '/media_shares/users/:user_id'       => 'media_shares#share'
  get '/media_shares/users/:user_id/*path' => 'media_shares#share'



  # api
  get    '/api/file/*path'            => 'media_resources_api#get_file'
  put    '/api/file_put/*path'        => 'media_resources_api#put_file'
  get    '/api/metadata/*path'        => 'media_resources_api#get_metadata'
  get    '/api/delta'                 => 'media_resources_api#get_delta'
  post   '/api/fileops/create_folder' => 'media_resources_api#create_folder'
  delete '/api/fileops/delete'        => 'media_resources_api#delete'





  # 公共资源
  resources :public_resources do
    collection do
      post :share
      put :upload
    end

    member do
      put :update_tag
    end
  end

  get '/public_resources/user/:id/file/*path' => 'public_resources#dir'
  get '/public_resources/user/:id/index_file/:file_entity_id' => 'public_resources#index_file'
  put '/public_resources/upload/*path' => 'public_resources#upload'
  get '/user_complete_search' => 'index#user_complete_search'
  get '/check_tip_messages' => 'index#check_tip_messages'

  get    '/tags/:tag_name'             => 'tags#show'
  get    '/tags/:tag_name/mine'        => 'tags#show_mine'
  get    '/tags/:tag_name/public'      => 'tags#show_public'
  get    '/tags/:tag_name/shared'      => 'tags#show_shared'

  resources :categories do
    member do
      get :lazyload_sub_dynatree
    end
  end

  resources :announcements do

    member do
      put :announce
    end
  end

  get '/c1/show' => 'c1#show'
  resources :e1
  resources :e2
  get '/f1/show' => 'f1#show'
  get '/d1/show' => 'd1#show'
  get 'g2/show'  => 'g2#show'
  get 'g3/show'  => 'g3#show'
  get 'g4/show'  => 'g4#show'

  get 'g1/show'  => 'g1#show'

  resources :i1
  resources :j1
  resources :k1
  resources :j2
  resources :j3

  resources :o1 do
    collection do
      get :zhaoyun
      get :zhugeliang
      get :faq_form
      get :question
    end
  end

  resources :test_papers

  resources :teaching_plans do
    member do
      get :preview
    end

    resources :chapters, :shallow => true do
      member do
        post :update_title
        post :update_desc
      end
      resources :course_wares, :shallow => true do
        member do
          post :update_title
          post :update_desc
          put :upload_file
          put :link_file
        end
      end
    end

    resources :test_questions, :shallow => true do
    end
  end


  

end

pin-edu-sns/app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < ApplicationController
  layout 'admin'
  before_filter :login_required
  before_filter :per_load

  def per_load
    @teacher = Teacher.find(params[:id]) if params[:id]
  end
  
  def index
    @teachers = sort_scope(Teacher).paginated(params[:page])
  end

  def new
    @teacher = Teacher.new
    @teacher.build_user
  end
  
  def create
    @teacher = Teacher.new(params[:teacher])
    if @teacher.save
      return redirect_to "/admin/teachers/#{@teacher.id}"
    end
    flash_error @teacher
    redirect_to "/admin/teachers/new"
  end
  
  # for ajax
  def destroy
    @teacher.remove
    render :text => 'ok'
  end

  def show
    @courses = @teacher.user.get_teacher_courses :semester => get_semester
  end

  def course_students
    @course = Course.find params[:course_id]
    @students = @course.get_current_students_of(@teacher.user)
  end

  def edit
  end

  def update
    if @teacher.update_attributes params[:teacher]
      return redirect_to "/admin/teachers/#{@teacher.id}"
    end
    flash_error @teacher
    redirect_to "/admin/teachers/#{@teacher.id}/edit"
  end

  def import_from_csv_page
  end

  def import_from_csv
    Teacher.import_from_csv(params[:csv_file])
    redirect_to "/admin/teachers"
  rescue Exception=>ex
    flash_error ex.message
    redirect_to "/admin/teachers/import_from_csv_page"
  end

  def password;end
  def password_submit
    if @teacher.update_attributes params[:teacher]
      return redirect_to "/admin/teachers/#{@teacher.id}"
    end
    flash_error @teacher
    redirect_to "/admin/teachers/#{@teacher.id}/password"
  end

end

pin-edu-sns/app/controllers/teachers_controller.rb
# -*- coding: utf-8 -*-
class TeachersController < ApplicationController
  before_filter :login_required
  before_filter :pre_load

  def pre_load
  end


  def index
    if current_user.is_student?
      _index_student
    elsif current_user.is_teacher?
      _index_teacher
    end
  end

  def _index_student
    @teachers = case params[:tab]
      when 'mine'
        sort_scope(Teacher).with_student(current_user).with_semester(get_semester)
      else
        sort_scope(Teacher)
      end.paginated(params[:page])
  end

  def _index_teacher
    @teachers = sort_scope(Teacher).paginated(params[:page])
  end

end

pin-edu-sns/app/views/admin/teachers/_teacher_list.html.haml
.attrs.ava
  .t2= sortable 'real_name', '教师姓名'
  .t2= sortable 'tid', '教师编号'
  .t2 用户名
  .t2 用户邮箱

- teachers.each do |teacher|
  .model.teacher
    .avatar= avatar teacher.user, :tiny
    .t2= teacher.real_name
    .t2= teacher.tid
    .t2= teacher.user.name
    .t2= teacher.user.email

    .ops
      - remove_url = admin_teacher_path(teacher)
      %a.remove{:href=>'javascript:;', :'data-url'=>remove_url} 删除
      %a.edit{:href=>"/admin/teachers/#{teacher.id}/edit"} 编辑
      %a.detail{:href=>"/admin/teachers/#{teacher.id}"} 详情

pin-edu-sns/app/views/admin/teachers/course_students.html.haml
- htitle '教师维护'

- hbreadcrumb '基础数据管理', '/admin'
- hbreadcrumb '教师维护', '/admin/teachers'
- hbreadcrumb @teacher.real_name
- hbreadcrumb @course.name + '学生列表'

.page-admin-model-show
  .field.avatar
    = avatar @teacher.user, :medium

  .data
    .field.name
      %label 教师姓名
      .v= @teacher.real_name

    .field.course
      %label 课程
      .v= @course.name

    .field.students
      %label 学生列表
      .v
        - @students.each do |student|
          .student= link_to student.real_name, admin_student_path(student)

.page-admin-go-back= link_to '返回教师详情', :back

pin-edu-sns/app/views/admin/teachers/edit.html.haml
- htitle '教师维护'

- hgoback admin_teachers_path
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '基础数据', '/admin'
- hbreadcrumb '教师维护', admin_teachers_path
- hbreadcrumb '修改教师信息'

.page-model-form
  = flash_info
  = form_for [:admin, @teacher] do |t|
    .field.need
      %label 真实姓名
      = t.text_field :real_name

    .field.need
      %label 教师编号
      = t.text_field :tid

    = t.fields_for :user do |user_f|
      .field.need
        %label 电子邮箱
        = user_f.text_field :email, :maxlength=>50


      .field.need
        %label 用户名
        = user_f.text_field :name, :maxlength=>50


      .field
        %label 性别
        = t.text_field :gender


      .field
        %label 部门
        = t.text_field :department


      .field
        %label 民族
        = t.select(:nation, nation_options, {:include_blank => true}, {:data => {:placeholder => '请选择'}})


      .field
        %label 政治面貌
        = t.text_field :politics_status


      .field
        %label 联系电话
        = t.text_field :tel


      .field
        %label 身份证号
        = t.text_field :id_card_number

      .field
        %label 教师介绍
        = t.text_area :description, :class => 'kind-editor'


      .field
        %label 备注
        = t.text_area :other_info, :class => 'kind-editor'

    .field.submit
      = jfsubmit '确定'
      = jfcancel '取消'

pin-edu-sns/app/views/admin/teachers/import_from_csv_page.html.haml
- htitle '教师维护'

- hgoback '/admin/teachers'
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '基础数据', '/admin'
- hbreadcrumb '教师维护', '/admin/teachers'
- hbreadcrumb '批量导入教师数据'

.page-model-form
  .page-admin-form-info
    .desc 请先下载 CSV 示例文件，按照给定格式填充数据，然后上传导入
    %a.download{:href=>'/csv_demo/teachers.csv'} 下载示例文件

  = flash_info
  = form_tag "/admin/teachers/import_from_csv",:method=>:post,:multipart => true do
    .field
      %label 选择 CSV 文件
      = file_field_tag :csv_file
    .field
      =jfsubmit '确定导入'

pin-edu-sns/app/views/admin/teachers/index.haml
- htitle '教师维护'

- hbreadcrumb '基础数据管理', '/admin'
- hbreadcrumb '教师维护'

- content_for :topbar do
  = jsearchbar search_admin_teachers_path

.page-admin-ops
  %a.create{:href=>'/admin/teachers/new'} 增加教师

.page-admin-models.teachers
  = render 'teacher_list', :teachers => @teachers

.page-paginate= will_paginate @teachers

pin-edu-sns/app/views/admin/teachers/index.html.haml
- htitle '教师维护'

- hgoback '/admin'
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '基础数据', '/admin'
- hbreadcrumb '教师维护'

= page_top_fixed 'buttons' do
  = page_buttons do |p|
    = p.button '增加教师记录', '/admin/teachers/new', :class=>'create'
    = p.button '批量导入教师', '/admin/teachers/import_from_csv_page', :class=>'import'

:ruby
  cols_hash = {
    :ops => 1,
    :real_name => 2,
    :tid => 2,
    :username => 2,
    :email => 4
  }

= page_top_fixed 'list-head' do
  .headtop
    = page_buttons do |p|
      = p.batch_destroy Teacher

    = list_pagination(@teachers)

  = page_list_head :cols=>cols_hash do |p|
    = p.checkbox
    = p.cell :ops, '操作'
    = p.cell :real_name, '教师姓名', :sortable=>true
    = p.cell :tid, '教师工号', :sortable=>true
    = p.cell :username, '用户名'
    = p.cell :email, '用户邮箱'

= page_model_list @teachers, :cols=>cols_hash, :class=>'admin-teachers' do |p|
  - teacher = p.model
  = p.checkbox(teacher)
  = p.cell :ops do
    %a.edit{:href=>"/admin/teachers/#{teacher.id}/edit"} 编辑
  = p.cell :real_name do
    %a.edit{:href=>"/admin/teachers/#{teacher.id}"}= teacher.real_name
  = p.cell :tid, teacher.tid
  = p.cell :username, teacher.user.name
  = p.cell :email, teacher.user.email

pin-edu-sns/app/views/admin/teachers/new.html.haml
- htitle '教师维护'

- hgoback '/admin/teachers'
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '基础数据', '/admin'
- hbreadcrumb '教师维护', '/admin/teachers'
- hbreadcrumb '增加教师'

.page-model-form
  = flash_info
  = form_for [:admin, @teacher] do |t|
    .field
      %label 真实姓名
      = t.text_field :real_name

    .field
      %label 教师编号
      = t.text_field :tid

    = t.fields_for :user do |user_f|
      .field
        %label 电子邮箱
        = user_f.text_field :email, :maxlength=>50
      .field
        %label 用户名
        = user_f.text_field :name, :maxlength=>50
      .field
        %label 密码
        = user_f.password_field :password, :value=>'', :maxlength=>32
      .field
        %label 确认密码
        = user_f.password_field :password_confirmation, :value=>'', :maxlength=>32

    .field
      %label 教师介绍
      = t.text_area :description, :value => '', :class => 'kind-editor'



    .field.submit
      = jfsubmit '确定'
      = jfcancel '取消'

pin-edu-sns/app/views/admin/teachers/password.html.haml
- htitle '教师维护'

- hgoback admin_teacher_path(@teacher)
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '基础数据', '/admin'
- hbreadcrumb '教师维护', '/admin/teachers'
- hbreadcrumb @teacher.real_name, admin_teacher_path(@teacher)
- hbreadcrumb '修改教师密码'

.page-admin-form
  = flash_info
  = form_for [:password_submit, :admin, @teacher] do |t|
    = t.fields_for :user do |user_f|
      .field.need
        %label 密码
        = user_f.password_field :password, :value=>'', :maxlength=>32
      .field.need
        %label 确认密码
        = user_f.password_field :password_confirmation, :value=>'', :maxlength=>32
    .field.submit
      = jfsubmit '确定'
      = jfcancel '取消'


pin-edu-sns/app/views/admin/teachers/show.html.haml
- htitle "教师维护 - #{@teacher.real_name}"

- hgoback '/admin/teachers'
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '基础数据', '/admin'
- hbreadcrumb '教师维护', '/admin/teachers'
- hbreadcrumb @teacher.real_name

.page-unfixed-head
  = page_buttons do |p|
    = p.button '修改信息', "/admin/teachers/#{@teacher.id}/edit"
    = p.button '修改密码', "/admin/teachers/#{@teacher.id}/password"

.page-model-show
  .page-admin-teacher
    = page_field :'base-info', :title=>'教师基础信息' do
      .base
        .avatar= avatar @teacher.user, :medium
        .name= @teacher.real_name
        .tid
          %span 工号：
          %span= @teacher.tid
      .detail
        .f
          .k 系统用户名：
          .v= @teacher.user.name
        .f
          .k 邮箱：
          .v= @teacher.user.email

    = page_field :desc, :title=>'教师简介' do
      = sanitize @teacher.description

    = page_semester_filters "/admin/teachers/#{@teacher.id}"

    = page_field :courses, :title=>'该学期下负责的课程' do
      - @courses.each do |course|
        :ruby
          students = course.get_current_students_of(@teacher.user)
          count = students.count
          course_teacher = CourseTeacher.get_by_params(course, Semester.now, @teacher.user)

        .course
          .course-info
            .name= link_to course.name, "/admin/courses/#{course.id}"
            .ops= link_to "分配学生", "/admin/course_teachers/#{course_teacher.id}/select_students_page"
            .ops{:style=>'margin-right:6px;'}= link_to "课时调整", "/admin/course_teachers/#{course_teacher.id}/edit_time_expression"

          .students-brief
            - students[0..4].each do |student|
              .student= avatar_link student, :tiny
            .desc= "等 #{count} 个学生"

            %a.open{:href=>'javascript:;'} 展开

          .students-detail
            .h
              .desc= "总共 #{count} 个学生"
              %a.close{:href=>'javascript:;'} 关闭

            .students
              - students.each do |student|
                .student
                  .avatar= avatar student, :tiny
                  .name= link_to student.real_name, admin_student_path(student)
          .course_change_records
            - course_teacher.course_change_records.each do |course_change_record|
              = course_change_record.start_date
              = course_change_record.end_date
              = link_to "删除", "/admin/course_change_records/#{course_change_record.id}", :method => :delete