pin-edu-sns/config/routes.rb
# -*- coding: utf-8 -*-
# -- 用户认证相关 --
def match_auth_routes
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'
  
  get  '/signup'        => 'signup#form'
  post '/signup_submit' => 'signup#form_submit'
end

# -- 设置 --
def match_account_routes
  # 基本信息
  get  "/setting"                     => "setting#base"
  put  "/setting"                     => "setting#base_submit"

  # 设置密码
  get '/setting/password'             => "setting#password"
  put '/setting/password'             => "setting#password_submit"

  # 头像设置
  get  "/setting/avatar"              => 'setting#avatar'
  get  '/setting/temp_avatar'         => 'setting#temp_avatar'
  post "/setting/avatar_submit_raw"   => 'setting#avatar_submit_raw'
  post "/setting/avatar_submit_crop"  => 'setting#avatar_submit_crop'
end

MindpinEduSns::Application.routes.draw do
  namespace :auth do
    # ---------------- 首页和欢迎页面 ---------
    root :to => 'sessions#new'
    match_auth_routes
    match_account_routes
  end

  ###
  namespace :admin do
    get '/search' => 'search#index'
    get '/search/:kind' => 'search#show'

    get '/setting/password'             => "setting#password"
    put '/setting/password'             => "setting#password_submit"


    # 管理员多级目录
    resources :upload_document_dirs do
      collection do
        post :create_folder
      end
    end

    resources :upload_documents do
      collection do
        post :file_put
      end
    end


    resources :teachers do
      collection do
        get :import_from_csv_page
        post :import_from_csv
      end
      member do
        get :password
        put :password_submit
        get 'course/:course_id', :action => 'course_students'
      end
    end

    resources :students do
      collection do
        get :import_from_csv_page
        post :import_from_csv
      end
      member do
        get :password
        put :password_submit
        put :upload_attachment
      end
    end

    resources :courses do
      member do
        get  :add_teacher_page
        put  :add_teacher
        get  :select_students
        put  :set_students
        get  :select_cover_page
        post :select_cover
      end
      collection do
        get  :import_from_csv_page
        post :import_from_csv
      end
      resources :course_resources, :shallow => true
    end
    resources :teams do
      member do
        get  :select_students
        put  :set_students
      end
      collection do
        get  :import_from_csv_page
        post :import_from_csv
      end
    end
    
    resources :categories do
      collection do
        get :import_from_yaml_page
        post :import_from_yaml
      end
    end

    resources :course_teachers do
      member do
        get :select_students_page
        put :select_students
        put :update_location
        get :edit_time_expression
        put :update_time_expression
        get :show_time_expression
      end

      resources :course_change_records, :shallow => true
    end

    resources :teaching_plans do
      collection do
        get :import_from_csv_page
      end
    end

    resources :course_surveys do
      collection do
        get :show_courses_by_semester
        get :show_teachers_by_course
      end
    end

    resources :mentor_notes

    resources :mentor_courses

    resources :course_score_records do
      collection do
        get :get_students_by_course
      end
    end
    
    resources :announcements

    resources :test_questions
    
    root :to=>"index#index"
  end
  ###
  # ----------------------------------------------------------------





  root :to => 'index#index'
  # 工作台
  get '/dashboard' => 'index#dashboard'
  # 搜索
  get '/search' => 'search#index'
  get '/search/:kind' => 'search#show'
  post '/batch_destroy' => 'index#batch_destroy'

  # --- 用户
  resources :users

  resources :teachers

  resources :students

  # --- 老师问答
  resources :questions, :shallow => true do
    resources :answers do
      collection do
        get :received
      end
    end
  end

  # ----------------------

  # 所有类型的评论都在这里，不单独定义
  resources :comments do
    collection do
      get 'show_model_comments'
      get 'received' # 我收到的评论
    end
  end
  
  resources :short_messages do
    member do
      put :read
    end

    collection do
      get :inbox
      get :outbox
    end
  end

  # --- 作业
  resources :homeworks do
    collection do
      post :create_teacher_attachment
      post :create_student_upload
    end
    
    member do
      get :download_teacher_zip
    end
  end

  resources :homework_assigns, :only => [:show] do
    member do
      get :download_student_zip
      put :set_finished
      put :set_submitted
    end
  end

  delete 'homeworks/teacher_attachment/:id/destroy' => 'homeworks#destroy_teacher_attachment'
  delete 'homeworks/requirement/:id/destroy' => 'homeworks#destroy_requirement'

  resources :homeworks, :student

  resources :teachers

  # 查看当前用户参与或负责的课程
  resources :course_surveys, :shallow => true do
    resources :course_survey_records
  end

  resources :mentor_students


  resources :courses do
    collection do
      get :curriculum
      get :next_for_student
      get :next_for_teacher
      get :subscriptions
    end

    member do
      put :subscribe
      get :edit_chapters

      get :nav_teachers
      get :nav_chapters
      get :nav_homeworks
      get :nav_ctest
      get :browse_chapters
    end

    resources :course_resources, :shallow => true
  end

  # --------------------

  # web
  get    '/file' => 'media_resources#index'
  get    '/file/*path' => 'media_resources#file', :format => false

  put    '/file_put' => 'media_resources#upload_file'
  post   '/file/create_folder' => 'media_resources#create_folder'
  delete '/file/*path' => 'media_resources#destroy'

  get    '/file_attr/*path/edit_tag' => 'media_resources#edit_tag'
  put    '/file_attr/*path/update_tag' => 'media_resources#update_tag'

  get  'file_show/*path' => 'media_resources#file_show', :format => false

  post '/upload' => 'file_entities#upload'
  post '/kindeditor_upload' => 'file_entities#kindeditor_upload'
  get  '/download/:download_id' => 'file_entities#download'
  post   '/file_entities/:id/re_encode'  => 'file_entities#re_encode'

  get '/media_resources/lazyload_sub_dynatree' => 'media_resources#lazyload_sub_dynatree'
  get '/media_resources/reload_dynatree'       => 'media_resources#reload_dynatree'
  put '/media_resources/move' => 'media_resources#move'

  resources :media_shares

  get '/media_shares/users/:user_id'       => 'media_shares#share'
  get '/media_shares/users/:user_id/*path' => 'media_shares#share'



  # api
  get    '/api/file/*path'            => 'media_resources_api#get_file'
  put    '/api/file_put/*path'        => 'media_resources_api#put_file'
  get    '/api/metadata/*path'        => 'media_resources_api#get_metadata'
  get    '/api/delta'                 => 'media_resources_api#get_delta'
  post   '/api/fileops/create_folder' => 'media_resources_api#create_folder'
  delete '/api/fileops/delete'        => 'media_resources_api#delete'





  # 公共资源
  resources :public_resources do
    collection do
      post :share
      put :upload
    end

    member do
      put :update_tag
    end
  end

  get '/public_resources/user/:id/file/*path' => 'public_resources#dir'
  get '/public_resources/user/:id/index_file/:file_entity_id' => 'public_resources#index_file'
  put '/public_resources/upload/*path' => 'public_resources#upload'
  get '/user_complete_search' => 'index#user_complete_search'
  get '/check_tip_messages' => 'index#check_tip_messages'

  get    '/tags/:tag_name'             => 'tags#show'
  get    '/tags/:tag_name/mine'        => 'tags#show_mine'
  get    '/tags/:tag_name/public'      => 'tags#show_public'
  get    '/tags/:tag_name/shared'      => 'tags#show_shared'

  resources :categories do
    member do
      get :lazyload_sub_dynatree
    end
  end

  resources :announcements do

    member do
      put :announce
    end
  end

  get '/c1/show' => 'c1#show'
  resources :e1
  resources :e2
  get '/f1/show' => 'f1#show'
  get '/d1/show' => 'd1#show'
  get 'g2/show'  => 'g2#show'
  get 'g3/show'  => 'g3#show'
  get 'g4/show'  => 'g4#show'

  get 'g1/show'  => 'g1#show'

  resources :i1
  resources :j1
  resources :k1
  resources :j2
  resources :j3

  resources :o1 do
    collection do
      get :zhaoyun
      get :zhugeliang
      get :faq_form
      get :question
    end
  end

  resources :test_papers

  resources :teaching_plans do
    member do
      get :preview
    end

    resources :chapters, :shallow => true do
      member do
        post :update_title
        post :update_desc
      end
      resources :course_wares, :shallow => true do
        member do
          post :update_title
          post :update_desc
          put :upload_file
          put :link_file
        end
      end
    end

    resources :test_questions, :shallow => true do
    end
  end


  

end

pin-edu-sns/app/controllers/admin/course_surveys_controller.rb
# -*- coding: utf-8 -*-
class Admin::CourseSurveysController < ApplicationController
  layout 'admin'
  before_filter :login_required
  before_filter :pre_load

  def pre_load
    @course_survey  = CourseSurvey.find params[:id] if params[:id]
  end

  def index
    kind = params['tab'] || "0"
    course_surveys = sort_scope(CourseSurvey)
    if kind != "0"
      @course_surveys = course_surveys.with_kind(kind).paginate(:page => params[:page])
    else
      @course_surveys = course_surveys.paginate(:page => params[:page])
    end
  end

  def new
    semester = Semester.get_by_value(Semester.now.value)
    @current_courses = semester.get_courses.map{|course|{:id => course.id, :name => course.name}}
  end

  def create
    @course_survey = CourseSurvey.new(params[:course_survey])
    if @course_survey.save
      return redirect_to "/admin/course_surveys/#{@course_survey.id}"
    end
    
    flash_error @course_survey
    redirect_to "/admin/course_surveys/new"
  end

  def show
  end

  def destroy
    @course_survey.destroy

    render :text => 'ok'
  end


  def show_courses_by_semester
    semester = params[:semester]
    semester = Semester.get_by_value(semester)
    courses = semester.get_courses.map{|course|{:id => course.id, :name => course.name}}

    render :json => courses
  end

  def show_teachers_by_course
    course_id = params[:course_id]
    semester = params[:semester]

    course = Course.find(course_id)
    semester = Semester.get_by_value(semester)

    teachers = course.get_teachers(:semester => semester).map{|user|{:id => user.id, :name => user.real_name}}

    render :json => teachers
  end

end

pin-edu-sns/app/controllers/course_surveys_controller.rb
# -*- coding: utf-8 -*-
class CourseSurveysController < ApplicationController
  before_filter :login_required
  before_filter :pre_load

  def pre_load
    @course_survey  = CourseSurvey.find params[:id] if params[:id]
  end

  def index
    surveys = CourseSurvey.with_user(current_user)

    @course_surveys = filter surveys do
      send('0') {:default}
      send('1') {surveys.with_kind('1')}
      send('2') {surveys.with_kind('2')}
    end
  end

  def show
  end

end

pin-edu-sns/app/helpers/course_survey_helper.rb
module CourseSurveyHelper

  def each_count(course_survey)

    records = course_survey.course_survey_records

    re = {}

    [
      :on_off_class,
      :checking_institution,
      :class_order,
      :prepare_situation,
      :teaching_level,
      :teacher_morality,
      :class_content,
      :knowledge_level,
      :teaching_schedule,
      :teaching_interact,
      :board_writing_quality,
      :has_courseware,
      :courseware_quality,
      :speak_level,
      :study_result,
      :teaching_result,
      :result_reason
    ].each do |stat_key|
      hash = records.group_by {|record| record.send(stat_key)}
      ['A', 'B', 'C'].each {|key| hash[key] ||= []}

      re[stat_key] = hash
    end

    re
  end



  def es_each_count(course_survey)

    records = course_survey.course_survey_es_records

    re = {}

    [
      :attend_class,
      :interesting_level,
      :understand_level
    ].each do |stat_key|
      hash = records.group_by {|record| record.send(stat_key)}
      ['A', 'B', 'C', 'D', 'E'].each {|key| hash[key] ||= []}

      re[stat_key] = hash
    end

    re
  end


  def list_resource_path_for(survey)
    kind = survey.kind
    record = (kind == '1' ? survey.course_survey_records : survey.course_survey_es_records)[0]
    return survey if current_user.is_teacher?
    return edit_course_survey_record_path(record, :kind => kind) if current_user.has_surveyed?(survey)
    new_course_survey_course_survey_record_path(survey, :kind => kind)
  end

end

pin-edu-sns/app/views/admin/course_surveys/_course_survey_list.html.haml
- @course_surveys.each do |course_survey|
  .model.course_survey
    .tite= course_survey.title

    .ops
      - remove_url = admin_course_survey_path(course_survey)
      %a.remove{:href=>'javascript:;', :'data-url'=>remove_url} 删除
      %a.detail{:href=>"/admin/course_surveys/#{course_survey.id}"} 详情

pin-edu-sns/app/views/admin/course_surveys/index.html.haml
- htitle '课程维护'

- hgoback '/admin'
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '课程调查', admin_course_surveys_path

= page_top_fixed 'buttons' do
  = page_buttons do |p|
    = p.button '新增课程调查', '/admin/course_surveys/new'

= page_top_fixed 'filters' do
  = page_filters '/admin/course_surveys' do |p|
    = p.filter '所有调查', :tab=>0, :default=>true
    = p.filter '类型一', :tab=>1
    = p.filter '类型二', :tab=>2

:ruby
  cols_hash = {
    :name => 3
  }

= page_top_fixed 'list-head' do
  .headtop
    = page_buttons do |p|
      = p.batch_destroy CourseSurvey

    = list_pagination(@course_surveys)

  = page_list_head :cols=>cols_hash do |p|
    = p.checkbox
    = p.cell :name, '标题', :sortable=>true


= page_model_list @course_surveys, :cols=>cols_hash, :class=>'admin-course-surveys' do |p|
  - course_survey = p.model

  = p.checkbox(course_survey)
  = p.cell :name do
    %a.detail{:href=>"/admin/course_surveys/#{course_survey.id}"}= course_survey.title

pin-edu-sns/app/views/admin/course_surveys/new.html.haml
- htitle '课程维护'

- hgoback admin_course_surveys_path
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '课程调查', admin_course_surveys_path
- hbreadcrumb '增加课程调查'

.page-model-form
  = flash_info
  = form_for [:admin, CourseSurvey.new] do |f|

    .field.need
      %label 标题
      =f.text_field :title
 
    .field
      %label 学期
      = f.select(:semester_value, Semester.get_recent_semesters.collect {|p| [ p.value ] }, {:prompt => true, :selected => Semester.now.value})

      = f.select(:course_id, @current_courses.collect {|p| [p[:name], p[:id]]}, {:include_blank => true}, {:data => {:placeholder => '请选择课程'}})
      
      .span{:id => 'teacher_notice'}
        选择课程后才能选择老师

      .span{:id => 'teacher_list', :style => 'display: none;'}
        = f.select(:teacher_user_id, '', {:include_blank => true})




    .field.need
      %label 调查类型
      =f.radio_button :kind, '1'
      %span  课程调查1

      =f.radio_button :kind, '2'
      %span  课程调查2
     

    .field
      = jfsubmit '确定'
      = jfcancel '取消'

pin-edu-sns/app/views/admin/course_surveys/show.html.haml
- htitle '课程调查'

- hgoback admin_course_surveys_path
- hbreadcrumb '首页', '/admin'
- hbreadcrumb '课程调查', admin_course_surveys_path
- hbreadcrumb @course_survey.title

:ruby
  case @course_survey.kind
  when '1'
    course_survey_records = @course_survey.course_survey_records
    survey_count = each_count(@course_survey)
    survey_list = 'survey_1_list'
  when '2'
    course_survey_records = @course_survey.course_survey_es_records
    survey_count = es_each_count(@course_survey)
    survey_list = 'survey_2_list'
  end

.page-unfixed-head

.page-model-show

  .page-admin-course-survey

    = page_field :'course-survey-info', :title=>'标题' do
      = @course_survey.title

    = page_field :'course-survey-info', :title=>'学生人数' do
      = course_survey_records.count

    = page_field :'course-survey-info', :title=>'调查详情' do
      = render survey_list, :survey_count => survey_count, :course_survey_records => course_survey_records